### ISSUE TITLE
Session Cell Styling

### ISSUE THREAD

**Issue by harrygfox** [OxfordAbstracts/elm-program-builder#45]
![screen shot 2017-03-03 at 14 15 54](https://cloud.githubusercontent.com/assets/7805691/23554197/f43d9c64-001b-11e7-8d73-5f2a69c6d125.png)

**Comment by harrygfox** [comment]
## BEM Names
.prog-cell
.prog-cell__header
.prog-cell__name
.prog-cell__body
.prog-cell__track
.prog-cell__location
.prog-cell__chair

**Comment by harrygfox** [comment]
@naazy I've reviewed your PR #55 and requested a few changes. Please could you update the comment above with any new BEM names you've included in the changes you've made? 🦀  🎰  🌜

**Comment by naazy** [comment]
This is complete
