### ISSUE TITLE
Preview to Open in New Window

### ISSUE THREAD

**Issue by harrygfox** [OxfordAbstracts/elm-program-builder#46]
When I click on the Preview button
A new browser window opens showing me a non-editable preview of the programme.

**Comment by iteles** [comment]
Why is this a requirement @harrygfox @naazy?

**Comment by naazy** [comment]
@iteles The preview essentially opens the same view as the publish view (no back button/toggle view at the top of the page) so I think @harrygfox thought it made more sense to just open it in a new window. I have implemented the change for now but it would be very easy to change back after user testing.

**Comment by naazy** [comment]
This is complete
